### ISSUE TITLE
How to make omaha client run silent?

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha#28]
My app installer already has its own install ui, so i wanna hide omaha ui, also don't wanna make user need to click OK in omaha ui after installing finish.
Do you know how to do it? any command line argument like /silent?
Thanks ^^

**Comment by shashkin** [comment]
The `/silent` command line switch allows to turn off Omaha UI
https://github.com/Crystalnix/omaha/blob/master/common/const_cmd_line.h#L165

If you want to run metainstaller silently, you need to run it as

    your_metainstaller.exe /silent /install

This method has several downsides:
- you have to run the metainstaller from the command line to be able to pass arguments to it.
- you have explicitly pass `/install` switch because it's not being added automatically when your metainstaller has non-empty command line arguments list
- this switch COMPLETELY turns off the UI which mean your user will not see neither "Preparing" nor "Connectiong to the Internet" nor "Waiting for download" nor "Failed to install" screens. This might be confusing because user may think that installation did not start
- it seems that with install UI turned off the action defined by `InstallerSuccessLaunchCmdLine` reg key will not be invoked

All these downsides make me think that the idea to turn the install UI off might not be so good.

There is the separate option: to suppress the final screen where user needs to click "OK".
All you need to do for that is to set `successsaction` attribute of the `postinstall` action to `exitsilently` or `exitsilentlyonlaunchcmd`.
https://github.com/Crystalnix/omaha/wiki/Omaha-Client-working-with-protocol#postinstall-event

**Comment by quyen194** [comment]
Thanks, I got it, I will try to do something else

**Comment by quyen194** [comment]
I don't know how to create pull request so i write it here:
Purpose: make omaha ui hide when start install app
Modify:
omaha\omaha\ui\progress_wnd.cc
void ProgressWnd::OnInstalling(const CString& app_name) {
...
Hide();  // end of function
}
omaha\omaha\ui\complete_wnd.cc
void CompleteWnd::DisplayCompletionDialog(bool is_success,
                                          const CString& text,
                                          const CString& help_url) {
...
// end of function
// better to use SendMessage to this dialog to click the close button
// but i don't know how to get this hwnd :P
// so try this
  BOOL hanle = FALSE;
  OnClickedButton(0, IDC_CLOSE, NULL, hanle);
}

**Comment by shashkin** [comment]
There's no need to modify `void CompleteWnd::DisplayCompletionDialog()` method when you can simply use `exitsilently` or `exitsilentlyonlaunchcmd` in `postinstall` event action.

WRT `void ProgressWnd::OnInstalling()` change, it looks like it permanently hides the window and there will be no way to leave it visible.
That is not acceptable in (our) case of completely silent application installer and this means we will not add this change to the project.

However, you can still use your changes in your fork if this is what you need.
Thanks.

**Comment by quyen194** [comment]
In my case, I have my own app installer'UI, so I need to hide omaha when start installing :dancers:
